### ISSUE TITLE
handler is still fired after unmount

### ISSUE THREAD

**Issue by hartatovich** [charleslxh/react-socket-io#11]
unmounting the Event component wont unsubscribe the handler for the eventname

`
function NotificationList({}) {

    const onMessage = (action) => {

        console.log("got new notification from socket", action);

    };

    return (
        <>
            {/*list component goes here*/}
            <Event event='notification' handler={onMessage}/>
        </>
    )
}
`

 "react": "^16.10.2"
 "react-socket-io": "^0.2.5"

**Comment by charleslxh** [comment]
Im my memory, event will unsubscribe when component unmount!

**Comment by bojan88** [comment]
The problem here is when we have an update before unmount. If the handler function is changed (prop updated with different function reference), `socket.off` is not going to remove it.

**Comment by Alexey-Khlebnikov** [comment]
@bojan88 is true
the cause is the reference to your function.

for example:
```
  constructor(props) {
    super(props);
    this.loadCorememData = () => {
      const { isAuth } = this.props;
      isAuth && this.props.dispatch('loadCorememData');
    }
  }

 ....

<Event event={'corememDataChanged'} handler={this.loadCorememData} />
```

it works well.
:)

**Comment by bojan88** [comment]
@hartatovich since you are using hooks, you can do this:
```
const onMessage = React.useCallback((action) => {
    console.log("got new notification from socket", action);
}, []);
```

It should fix your issue. It's basically what Alexey proposed, but with hooks
