### ISSUE TITLE
I'm getting PropTypes error in Create-React-App

### ISSUE THREAD

**Issue by dachinat** [charleslxh/react-socket-io#6]
When using create-react-app requiring library with 

```
import { Socket } from 'react-socket-io';
```

casuses error

<img width="548" alt="screen shot 2018-05-06 at 12 13 56 pm" src="https://user-images.githubusercontent.com/22872749/39671332-284d52e4-5127-11e8-9752-fc1b0b3b71e0.png">

Any idea how to get around this?

**Comment by dachinat** [comment]
I have overcame this by using `yarn add https://github.com/charleslxh/react-socket-io.git`

**Comment by MahmoudAwwad94** [comment]
I have overcame this by getting inside the react-socket-io node_module and execute npm install again
