### ISSUE TITLE
Any plans to update 16.3?

### ISSUE THREAD

**Issue by byronrau** [charleslxh/react-socket-io#8]
Any plans to update to 16.3? using the Context API?

**Comment by charleslxh** [comment]
@byronrau Can you create a PR? thx!

**Comment by apalanki** [comment]
@charleslxh I created a PR to upgrade to 16.8.x, can you take a look when you get a chance?

**Comment by charleslxh** [comment]
@apalanki 

Thank you for this PR.

I merged it and release a new version [0.2.5](https://www.npmjs.com/package/react-socket-io) to  NPM Registry.

see [tag v0.2.5](https://github.com/charleslxh/react-socket-io/tree/v0.2.5).
